ics-py/ics-py

ics/event.py
ics/icalendar.py
ics/parse.py
ics/utils.py
tests/component.py
tests/contentline.py
tests/event.py
tests/fixture.py
tests/parse.py

This pull request adds a thing and fixes many little details.
- Added support for URLs to Event.
- Fixes according to RFC5545:
+ [Lines are separated by CRLF (`\r\n`)](https://tools.ietf.org/html/rfc5545#section-3.1). Tests had to be adapted,  `str.split('\n')` is changed to the more generic `str.splitlines()`
+ [names of properties etc. are case-insensitive](https://tools.ietf.org/html/rfc5545#page-11). So in `ContentLine.__init__` `name` is uppercased for consistency and easier comparing. Some tests had to be adapted.
- PEP8 Fixes:
+ assigning lambdas to a variable is discouraged, (In eventlist.py there are a lot of these assignments left. I didn't work through this code yet.)
+ formating issues.
- Other fixes:
+ Use `str.split(splitChar, 1)` where appropriate
+ use `isinstance(foo, …

Add urls to events, fixes according to the specs, PEP8 fixes

---

ics/event.py
ics/utils.py
tests/event.py

The current incarnation always appends a timestamp and the `Z` timezone specifier whenever you have an all day event. This means that I end up seeing events from `20151220T190000EST` until `20151220T190000EST` because of my timezone (EST -0500).
This pull request makes sure that anyone who imports the calendar has an all day event in their current timezone instead of 24 hours from UTC.
> **Value Type**
> The default value type is DATE-TIME. The time value MUST be one of the forms defined for the DATE-TIME value type. The value type can be set to a DATE value type.
Fixes #73

Use shorthand DTSTART;VALUE=DATE:YYYYMMDD for all day events

---

ics/component.py
ics/icalendar.py

This PR adds the ability to specify the default parameters in `@Calendar._extracts` decorator.
If the `required` param is specified but not found, it allows to gracefully assume a default value.
Because I have encountered that a few iCal files have missing `VERSION` key. Rather than raising a TypeError, it makes more sense to allow this.
I'm not sure if this should be a feature, though -- since I only have one anecdotal evidence, so feel free to discuss.
Thanks!

Adds the ability to specify `default` parameters

---

ics/parse.py

ParseError is raised when '=' is not in paramstr.
But the error message that's returned says '=' is not in line (not paramstr).

Reference paramstr instead of line in ParseError

---

README.rst

In README.rst under Quickstart, the guide uses append instead of add on a set objects. Sets cannot be appended

Add instead of append

---

ics/icalendar.py
tests/alarm.py
tests/calendar.py
tests/event.py
tests/todo.py

Some import and test code were using a list instead of a set.

events/todos: use set not list

---

AUTHORS.rst
CHANGELOG.rst
ics/alarm.py
ics/event.py

It looks like Google ICS files may include a VALARM action of None which throws an error. Although this type isn't mentioned in the RFC that I could find, I think ignoring these alarms is valid based on the action type and should throw an error given the popularity of Google Calendar.
This addresses: https://github.com/C4ptainCrunch/ics.py/issues/127

Support VALARM of ACTION:NONE

---

AUTHORS.rst
CHANGELOG.rst
ics/alarm.py

TRIGGER DURATIONs can also take the form `TRIGGER;VALUE=DURATION:-PT30M`. The existing logic only accounts for `TRIGGER:-PT30M`.
This can be tested with any of the NHL ical schedules from this season, e.g. https://www.stanza.co/api/schedules/nhl-sabres/nhl-sabres.ics .
Before:
```python
In [2]: cal = ics.Calendar(requests.get('https://www.stanza.co/api/schedules/nhl-sabres/nhl-sabres.ics').text)
ParserError: Could not match input to any of ['YYYY-MM-DDTHH:mm']
```
After:
```python
In [2]: cal = ics.Calendar(requests.get('https://www.stanza.co/api/schedules/nhl-sabres/nhl-sabres.ics').text)
In [3]: cal.events[0].alarms[0].trigger
Out[3]: datetime.timedelta(0, 1800)
```

Improve TRIGGER DURATION parsing logic

---

CHANGELOG.rst

This confused me for a bit. Probably worth noting.

Add note that EventList was removed in 0.4

---

AUTHORS.rst
ics/alarm.py

Add __hash__ method to the Alarm class to make it hashable
in order to be able to add an Alarm list to the Events.alarms set.
Fixes #130

Make Alarm hashable

---

ics/event.py

Hi, 👋
Thank for this great project.
With this PR I am proposing to fix : 
- Even when passing an Organizer to Event object __init__, it is not set and therefor not serialized.
What can cause a missing Organizer in ics ?
- For ex. it can make Outlook believe that there is not from field in a email. (Weird, isn't it ?)
Thank.

Bugfix in Event constructor self.organizer is None

---

ics/timeline.py

remove useless `day` argument from `Timeline.today()`

---

CHANGELOG.rst
ics/event.py
tests/event.py

This reverts commit ed14cde096ad5b50bfa768c1fd32892eba744087.
See discussion here:
https://github.com/C4ptainCrunch/ics.py/pull/222#issuecomment-585215211
We want to only include simple changes in the directly next release and
wait with the complicated all-day and event timestamp handling issues
for the then following dedicated release, which is prepared in
https://github.com/C4ptainCrunch/ics.py/pull/222.

Revert "Improve all-day event handling." (#155/#204)

---

src/ics/icalendar.py

Greetings! Big fan, small fix. Read the guidelines, don't think this warrants opening an issue, but do let me know if you need a test for this.
Fixes `<Calendar with 0 event and 0 todo>` [sic]

Fix plural form of events and todos

---

.github/workflows/pythonpackage.yml
README.rst
poetry.lock
pyproject.toml
src/ics/attendee.py
src/ics/contentline/container.py
src/ics/converter/base.py
src/ics/converter/component.py
src/ics/converter/types/various.py
src/ics/converter/value.py
src/ics/event.py
src/ics/timespan.py
src/ics/timezone/converters.py
src/ics/valuetype/generic.py
src/ics/valuetype/special.py
tox.ini

Python 3.10 is out since a few days, time to officially support it 🎉
Python 3.6 [will be EOL](https://www.python.org/dev/peps/pep-0494/#and-beyond-schedule) by the end of the year (so probably before the next ics release) so i'm suggesting dropping active support too.

Drop Python 3.6 and add support for 3.10

---

.bumpversion.cfg
doc/timezone.rst
src/ics/icalendar.py
tests/issues/gh251.py

This PR will include the version of ics.py in the PRODID field, which currently defaults to `ics.py - http://git.io/lLljaA`, so that an empty calendar will now look like this:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py 0.8.0-dev - http://git.io/lLljaA
END:VCALENDAR
```
This should help with identifying the affected versions of bug reports. One could also include further system information for debugging such as the python interpreter and version and the OS, although this might be a problem with privacy (and possibly security, if we report a vulnerable version). Furthermore, including more information in the PRODID also makes deterministic outputs harder to get, e.g. see the updated bumpversion config. So I'm not 100% sure we should do this at all, but using only the version might be a …

Include ics.py version in PRODID field

---

.github/workflows/pythonpackage.yml
tox.ini

Minor changes to not have a fixed 3.11 alpha release selected and to include the latest pypy 3.8 beta, which should already be pretty stable and actually also works flawlessly.

use latest python 3.11 alpha and add pypy 3.9

---

.github/workflows/pythonpackage.yml
src/ics/converter/types/various.py
tox.ini

+ ignore a hack with rrule._rdate and rrule._exdate that was failing the build

Pin mypy to a specific version to avoid breakages of main in the future

---

.readthedocs.yaml

See https://github.com/ics-py/ics-py/issues/314#issuecomment-1143424444
Build still works https://readthedocs.org/projects/icspy/builds/17064044/

Use pip and not poetry in the ReadTheDocs build

---

doc/howtos/quickstart.rst

Checked the rest of the docs and did not find any more occurrences.

Fix date format in documentation quickstart

---

tests/issues/gh251.py

Update test to use a fixture based on discussion in https://github.com/ics-py/ics-py/pull/325 since this was the test I copied from. This is a very minor improvement for this test, and more meaningful in the timeline test, but seemed worth cleaning up anyway.

Update test to use a fixture

---

poetry.lock
pyproject.toml
tests/timeline.py
tox.ini

Add simple test cases for the calendar timeline to increase test coverage for timeline (from 35% to >90% according to tox codecov)
The motivation is mostly about learning the code base, and this seemed like something useful to do in the process.

Add test coverage for timeline (from 35% to >90%)

---

README.rst
doc/examples.rst
ics/component.py
ics/icalendar.py

In 0.8, there are some breaking changes to `str(calendar)` which can cause data loss if users update ics carelessly, so we should have at least one release that warns of this (see [here](https://github.com/ics-py/ics-py/issues/245#issuecomment-1059507609)).
As a stable 0.8 release is still somewhat in the future and we have some not-yet released fixes for version 0.7 lying around, my suggestion would be to add these warnings in a v0.7.1 release and push out all those fixes very soon (we could've actually done this in 2020 to give users even more time to prepare :see_no_evil:).
I suggest that the implicit serialization in `Calendar.__iter__` should go in version 0.8, while the changed behaviour of `Calendar.__str__` is deferred to v0.9. For `__str__` in version 0.8, I'll keep the old …

add warnings about breaking changes to Calendar.__str__ and __iter__ in v0.7(.1)

---

tests/event.py

Improve test coverage for `event.py`, getting closer to 90% coverage.
Coverage improvements include duration, gt/lt comparisons, within, includes, and intersects methods.
Issue #245

Increase test coverage for Event class by 10%

---

pyproject.toml

@C4ptainCrunch This oneline change fixes the CI failures for #395. This PR is against that branch, so if you merge this your PR should pass. Let me know if you have any questions.
`setuptools` is needed by `lipsum` and `setuptools` is no longer provided by default in Python 3.12.

Add setuptools to test requirements

---

AUTHORS.rst
src/ics/icalendar.py

There were some trivial grammatical errors in `icalendar.py` which would make the documentation for `parse_multiple` harder to read. There was also an incorrect article of speech in the class comment for `Calendar`, so that was fixed.

Fix grammatical errors for readability
