ics/utils.py

use TZID as time zone if possible

---

ics/event.py
tests/event.py
tests/fixture.py

Hi,
This PR adds TRANSP attribute support: http://www.kanzaki.com/docs/ical/transp.html
I need this attribute to know if it's a free or busy event.
Thanks for your remarks.
Have a nice day.

Add TRANSP attribute support

---

CONTRIBUTING.rst
ics/component.py
ics/event.py
ics/eventlist.py
ics/icalendar.py
ics/parse.py

Some minor changes to spelling and grammar in the documentation to help with clarity.

Tidy documentation for spelling/grammar

---

ics/event.py
tests/event.py

Closes https://github.com/C4ptainCrunch/ics.py/issues/59

Enh event order

---

CHANGELOG.rst
ics/event.py
ics/parse.py
ics/todo.py
ics/utils.py
requirements.txt
tests/event.py
tests/todo.py

Thanks to @muffl0n @e-c-d and @chauffer
Closes #139
Closes #145
Closes #77

Apply patch from #77

---

CHANGELOG.rst
ics/event.py

Fix all-day events lasting multiple days

---

AUTHORS.rst
CHANGELOG.rst
ics/event.py
meta.py
setup.py
tests/event.py

This pull request adds last modified attribute, which is very useful, if you want to check if/when the event has changed.
I also removed meta symlink, because it was outputting import errors, I hope that's okay.

Feature: Last modified attribute

---

ics/alarm/email.py
tests/alarm.py

fixes #213, but probably should also have tests for this

Add missing implementation for abstract EmailAlarm.action property

---

ics/serializers/icalendar_serializer.py
tests/calendar.py

fixes #55 and also includes a test

Make sure version is given first

---

AUTHORS.rst
CHANGELOG.rst
ics/__meta__.py

See [milestone](https://github.com/C4ptainCrunch/ics.py/milestone/7) for progress.

Release version 0.7

---

ics/serializers/alarm_serializer.py

fix "falsey" alarm trigger (i.e. timedelta(0)) being interpreted as None

---

AUTHORS.rst

- Remove duplicated content.
- Update some dead links.
- Use "secure" URLs only.
- Add details.

docs(AUTHORS.rst): Polish contents.

---

.gitignore
.readthedocs.yml
doc/Makefile
doc/conf.py
poetry.lock
pyproject.toml

Closes #271. The resulting build from this PR is show there: https://icspy.readthedocs.io/en/fix-docs/

Fix Read the Docs build

---

poetry.lock
pyproject.toml
src/ics/event.py
src/ics/icalendar.py
src/ics/timespan.py
tests/issues/gh251.py
tests/issues/gh269.py
tests/normalization.py

add calendar-wide timezone conversion/replacement/normalization

---

pyproject.toml
src/ics/contentline/container.py
tests/contentline/__init__.py
tests/valuetype/text.py

add (content-) line wrapping to stay withing the 75 char limit

---

src/ics/converter/base.py
tox.ini

See https://github.com/ics-py/ics-py/pull/301#issuecomment-1005165511

Fix missing type annotation due to a new version of mypy

---

.github/workflows/pythonpackage.yml

Otherwise, pull requests from forks don't run the tests

Also run Github Action on pull requests 

---

CONTRIBUTING.rst

Rewrote the contribution docs to match the new [release workflow](https://github.com/ics-py/ics-py/pull/274) and tooling.
Could not test the actual release process but hopefully close enough.

Contribution docs update

---

ics/serializers/event_serializer.py

Fixes https://github.com/ics-py/ics-py/issues/360

Fix deprecation warning while serializing event alarm

---

.github/workflows/pythonpackage.yml
pyproject.toml
tox.ini

Changes:
* mypy python_version
* docs and checks now run with 3.11
* add PyPI classifier

Python 3.11 is released, update where possible to 3.11 on our side
